### ISSUE TITLE
Interest in static binaries? / Nix instructions

### ISSUE THREAD

**Issue by martinbaillie** [iann0036/iamlive#1]
Would you be interested in statically compiling the release binaries? No worries if not, just close this issue off.

In case it helps other Nix users passing by: patching the ELF will suffice until Go 1.16 RCs hit NIxpkgs.
```shell
; patchelf \                              
      --set-interpreter "$(cat $NIX_CC/nix-support/dynamic-linker)" iamlive
```

**Comment by iann0036** [comment]
Happy to do it, but I'm not very familiar with how that works. Do you have a build example (and does it change per OS)?

Currently using [this GitHub action](https://github.com/iann0036/go-release-action/blob/master/release.sh#L50) to build and release.

**Comment by martinbaillie** [comment]
I think this update to the Action parameters should do it

**Comment by martinbaillie** [comment]
Thanks @iann0036. Can confirm that did it.

**Comment by iann0036** [comment]
Cheers, appreciate the help!
