### ISSUE TITLE
Segfault when running with CSM enabled via env var on linux amd64

### ISSUE THREAD

**Issue by bvtujo** [iann0036/iamlive#10]
Running this command:
```sh
$ iamlive --profile default
```
on version `v0.12/iamlive-v0.12-linux-amd64.tar.gz` with the `AWS_CSM_ENABLED=true` environment variable set in the window where I'm doing my calls results in the following segfault and trace:
```sh
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ssm:GetParametersByPath",
                "cloudformation:DescribeStacks",
                "sts:AssumeRole",
                "resource groups tagging api:GetResources",
                "cloudformation:GetTemplate",
                "cloudformation:DeleteStack",
                "iam:ListRolePolicies",
                "iam:DeleteRolePolicy",
                "iam:DeleteRole",
                "ssm:DeleteParameter"
            ],
            "Resource": "*"
        }
    ]
}
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.getDependantActions(0xc0000d0080, 0x2, 0x2, 0xd, 0xc0000d0080, 0x2)
        /github/workspace/main.go:275 +0x6dd
main.getPolicyDocument(0xc0005c20d8, 0x16, 0x5)
        /github/workspace/main.go:178 +0x3ca
main.writePolicyToTerminal()
        /github/workspace/main.go:221 +0x4e
main.handleLoggedCall(...)
        /github/workspace/main.go:212
main.listenForEvents()
        /github/workspace/main.go:159 +0x453
main.main()
        /github/workspace/main.go:360 +0x8b
```

It doesn't seem like the oddly formatted "resource groups tagging api" action is the culprit. I am unfortunately unsure what call I made immediately before this fault, as I was testing out this tool to discover the actual IAM calls made by a different CLI. Some possibilities are Secrets Manager, CodePipeline, and S3.

**Comment by iann0036** [comment]
Hey @bvtujo,

Thanks heaps for raising. Looks like you hit an unexpected condition in the way permissions were being handled - apologies for that. The latest version (v0.13 or HEAD) should have the fixes. Let me know if that solves your issue.

**Comment by bvtujo** [comment]
No problem! I love what you're doing with this tool; it's an incredibly useful idea.
