### ISSUE TITLE
CDK Support

### ISSUE THREAD

**Issue by ciaranevans** [iann0036/iamlive#13]
Hey, this utility looks like just the thing I want to narrow down permissions needed for CI users to have the ability to run CDK commands.

I'm giving the utility a go now and I'm wondering if I should be getting output or not?

I'm doing

```
iamalive --set-ini --profile <my-profile>
```

And

```
cdk diff
```

But getting no output at the moment

**Comment by ciaranevans** [comment]
I'd missed the section on providing:

```
AWS_CSM_ENABLED=true
AWS_CSM_PORT=31000
AWS_CSM_HOST=127.0.0.1
```

It works a charm! Bravo @iann0036

**Comment by ciaranevans** [comment]
Hi @iann0036,

I'm re-opening this one just to ask a follow-up question.

When running `iamlive` the tool captures the permissions that the locally running CDK commands use, it doesn't however capture the commands CFN uses to create resources. Is there a way this could be incorporated? 

I imagine this would be quite a task... I'd love to be able to do a full deploy of my stack and have a entire list of the permissions something like a CI user would need to be able to deploy the stack.

**Comment by hoegertn** [comment]
As you said, CFN creates the resources so I don't think there is a way to see what exactly CFN does here. You would need to inspect the CloudTrail logs for this.

**Comment by iann0036** [comment]
Hey @ciaranevans,

There's no way for this tool to capture what CFN is doing under the hood as we don't have access to the control plane.

I do have [another project](https://github.com/iann0036/aws-leastprivilege) that made a start on this, mostly by exhaustively changing every possible CFN property, IAM denying everything explicitly, and seeing what the CFN stack events say. Didn't get too far before it became too complex - it will fall back on the CloudFormation Registry (action-only) permissions where available.

**Comment by ciaranevans** [comment]
Cool, no worries, just wondering what the possibilities were!

I might have a look at the Cloudtrail option. Maybe a little boto3 based app could be used as a one-time thing to scrape CloudTrail.
