### ISSUE TITLE
Policies shouldn't be generated when `Action` is null

### ISSUE THREAD

**Issue by castrapel** [iann0036/iamlive#15]
Hello! Thank you for iamlive!

I ran an `aws sts get-caller-identity` command with temporary assume-role credentials form an IAM role. iamlive generated the following policy, which is invalid. I don't think any permissions are needed for this particular call. Should iamlive just *not* generate a policy when Action is null?

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": null,
            "Resource": "*"
        }
    ]
}
```

![image](https://user-images.githubusercontent.com/7538233/108399165-b17ea200-71ce-11eb-8fe7-dbf18a1c7c1f.png)

**Comment by iann0036** [comment]
Hi @castrapel,

Thanks for raising!

I've pushed a fix for this so a null policy shouldn't generate (v0.17). Let me know if you have any issues.
