### ISSUE TITLE
Feature Request: Support multiple clients and remote deployment 

### ISSUE THREAD

**Issue by Isan-Rivkin** [iann0036/iamlive#16]
Hi, great tool! 
I am looking to use this in a slightly "advanced" use case. 
Due to different constraints and friction, I want to enable running this as a remote service and session aware. 

**Remote Service:**
* Deploy this as a remote UDP server with support for k8s. 
* Similar to the `output` flag functionality store policies in files.
* Expose HTTP endpoint to view generated policies based on the file name created 

**Session Aware:** 
The idea is that to support multiple clients the service needs to:
* Know which request belongs to which client and split it into logical partitions per client. 
* Context/Partitions can be extracted from things like the AccessKey ID / User-agent/ Source IP+Port. It is also possible to get the actual IAM user name from the access key id. 
* Merge session policies to one: Since a session can contain more than 1 request maybe merge all the policies into one to simplify operations. 

**A Real-life use case example:**
- A developer that runs a pipeline of spark jobs running in Airflow orchestrator. 
- The spark job uses the spark SDK to make several calls to AWS services behind the scenes in one single spark function. 
- The developer receives a "permission denied" error but not sure what permission they need and where is the problem exactly since the direct API calls are abstracted. 

The goal is to troubleshoot minimize the time it takes to troubleshoot and support the least privilege principle. 
So this would be solved really quickly, the developer would add the required environment variables to the spark job and rerun it. 

Then the developer would go to the iamlive HTTP endpoint URL and find his session details with the policy created. 

I have several ideas of how this could be implemented and would love to help! 

If this is something you can consider adding Id love to talk more about it and elaborate.

**Comment by iann0036** [comment]
Hey @Isan-Rivkin,

Thanks for raising!

Hang tight on this for about a week or so. There's a new release in the works that'll solve some (not all) of the above.

**Comment by Isan-Rivkin** [comment]
@iann0036  Awesome, thanks! I'll close this issue then and maybe reopen it if necessary in the future.
