### ISSUE TITLE
'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by serverlesspolska** [iann0036/iamlive#18]
Hello

I've downloaded the binary for mac [iamlive-v0.18-darwin-amd64.tar.gz](https://github.com/iann0036/iamlive/releases/download/v0.18/iamlive-v0.18-darwin-amd64.tar.gz) and:
1. It does not work
2. It broke my `aws` CLI. Every command that I execute using CLI ends with `'str' object has no attribute 'get'` - that's the whole output, the command is not executed at all.

**Comment by iann0036** [comment]
Hey @serverlesspolska,

Apologies for the issue!

There's probably something going on with your `~/.aws/config` file? iamlive attempts to set the CSM flag if you use the `--set-ini` option. Check that file to see if there's an entry within that doesn't have an `=` sign within it.

**Comment by serverlesspolska** [comment]
there was
```
s3 = 
```

which was causing the problem. Removing that line fixed the problem.
