### ISSUE TITLE
[Request] Required permissions as HTML/Markdown

### ISSUE THREAD

**Issue by skyzyx** [iann0036/iamlive#23]
After collecting the permissions which are required, being able to output that list as Markdown (preferred) and/or HTML would be handy for the documentation for the code.

Presently, a JSON-formatted IAM policy is the default. Options could be a list or table (assuming you could justify more than one column of data).

Example:

```markdown
* `ec2:AuthorizeSecurityGroupEgress`
* `ec2:AuthorizeSecurityGroupIngress`
* `ec2:CreateLaunchTemplate`
* `ec2:CreateSecurityGroup`
* `ec2:DeleteLaunchTemplate`
* `iam:GetPolicy`
* `iam:GetPolicyVersion`
* `iam:GetRole`
* `iam:ListAttachedRolePolicies`
* `sts:GetCallerIdentity`
```

**Comment by iann0036** [comment]
I'd like to hold off on roughly specialised formats unless there is strong demand (if you're reading this ticket, please 👍 if you'd like this).

In the meantime, you should be able to accomplish this with something like:

```
cat policy.json | jq -r '["* `" , (.Statement[0].Action | join("`\n* `")) , "`"] | add'
```

**Comment by skyzyx** [comment]
👍🏻
