### ISSUE TITLE
[BUG] Creating AWS VPC with terraform is not tracked by iamlive

### ISSUE THREAD

**Issue by unfor19** [iann0036/iamlive#32]
Hey @iann0036 , I've tried to create the [AWS VPC Module](https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/latest) with Terraform, using `iamlive` in Proxy Mode.

## Issue

 `iamlive` did not track the required permissions for creating an AWS VPC with terraform

## Details

```
terraform apply
# request proxied through iamlive
```

The IAM policy that was generated for my `dummy-user` by `iamlive`:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "sts:GetCallerIdentity",
                "ec2:DescribeAccountAttributes",
                "ec2:CreateVpc"
            ],
            "Resource": "*"
        }
    ]
}
```

I updated the `dummy-user`'s IAM policy with the above generated IAM policy. And I still got the following error

```bash
terraform apply
...
# Error: Error creating VPC: UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: ENCODED_MESSAGE
```

I decoded the ENCODED_MESSAGE by following this [tutorial by AWS](https://aws.amazon.com/premiumsupport/knowledge-center/ec2-not-auth-launch/)

```bash
aws sts decode-authorization-message --encoded-message "$ENCODED_MESSAGE" | jq -c '.DecodedMessage | fromjson | .context.action'

# Output:
# "ec2:CreateTags"
```

This makes sense, `dummy-user` is not allowed to `ec2:CreateTags`, but why didn't `iamlive` track this permission?

So now I'm thinking, does `iamlive` track encoded messages and tries to decode them?

P.S- I also tried `aws s3 cp myfile s3://mybucket/myfile` and the `s3:PutObject` wasn't tracked by `iamlive`, as if it isn't even proxied via `iamlive`, an IAM Policy wasn't generated. When I tried to copy the file from the bucket to my machine with `aws s3 cp s3://mybucket/myfile ./myfile` , I saw that `iamlive` was able to generate an IAM Policy. Not sure if it helps, but it might be related.

**Comment by unfor19** [comment]
After some digging, I think it's because the default mode for AWS SDK is to use the [DryRun mode](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/ec2-api.pdf). So it's probably `DryRun=true` by default.

![image](https://user-images.githubusercontent.com/15122452/115968534-1644d880-a541-11eb-8470-90f32c680388.png)

Needs to be handled somewhere in `iamlive`, so that any `DryRun` request is set to `false`, this way AWS SDK won't check for existing permissions, but will actually perform the action and then it will be tracked by `iamlive`.

Another option would be to sniff `DryRun` calls, though it sounds tougher.

**Comment by iann0036** [comment]
Hey @unfor19,

Thanks for raising!

I think you may be slightly overthinking the issue here. iamlive is built using a [map](https://github.com/iann0036/iamlive/commit/fc141109e74af1ab59f63c60cce1b862f1b39392#diff-aab0e8ac39881350bc8b718e6872b7250d2f7d9b1a1533f6d19a3fc487d736e9R19050) of SDK actions to IAM actions. Some of this is based off of the [SAR](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonec2.html#amazonec2-vpc), however the SAR has omitted the Dependant Action of `ec2:CreateTags` for `CreateVpc` in this case as it seems to only be required if tags are specified.

I've adjusted the map for this specific call to conditionally add the `ec2:CreateTags` permission, but there will likely be others based on tags that need to be defined. Feel free to raise them here if you see them.

**Comment by unfor19** [comment]
@iann0036 is there a way to intercept AWS response, decode and add permissions according to that? :)

**Comment by iann0036** [comment]
Probably, however I do intend for iamlive to be an entirely passive tool that does not make additional calls (i.e. sts.DecodeAuthorizationMessage). Feel free to fork and add the feature as you please, but note that I probably won't merge.

**Comment by unfor19** [comment]
If you're not going to merge it then I'll drop it.

To conclude - if this sort of errors happen, the fix is to add the missing permissions to `iamlive` ?

**Comment by iann0036** [comment]
Yep, that's right. Specifically the `map.json` file would be the likely one to be changed.

**Comment by unfor19** [comment]
@iann0036 I don't want to spam you with another issue, and I think the following one is related.

I think I hit a roadblock with Terraform. I've tried to create a `Subnet` and an `Internet Gateway`, and apparently, they both need `ec2:CreateTags` when using the Terraform AWS VPC module.

Seems like it's impossible to automatically cover all the required permissions unless we add them one by one manually to `iamlivecore/map.json` 😞 

Any suggestions on how to tackle this challenge?

**Comment by iann0036** [comment]
> unless we add them one by one manually to iamlivecore/map.json

Yep. I'm working with the AWS IAM team on some of these challenges, specifically the lack of documentation for these dependant actions. Until then, I'll manually update the map (so I'll add those today).

**Comment by unfor19** [comment]
That sounds amazing! If you solve this puzzle, determining IAM permissions will be super easy.

For now, I'm using my `automate.sh` script, which is not "production-ready" yet. The way I currently find out which permissions are missing - 
1. invoke terraform apply
2. read logs in iamlive
3. update IAM policy in AWS according to the one generated by iamlive
4. invoke terraform apply
5. check if "encoded messages" exist, if so, decode them and stop the process
6. if not failed in 5, go over to step one

So each time I invoke the script I either get an updated IAM policy in AWS, or an error message which includes the missing permissions.

```bash
>> [LOG]: Waiting 5 seconds for iamlive to be ready
>> [LOG]: Passed Proxy Server check
>> [LOG]: Attempting to copy /home/meir/.iamlive/ca.pem from the container iamlive
>> [LOG]: Successfully copied
>> [LOG]: Executing: cd /home/meir/iamlive/.myterraform ; terraform apply -auto-approve
module.vpc.aws_vpc.this[0]: Refreshing state... [id=vpc-****]
module.vpc.aws_route_table.private[0]: Refreshing state... [id=rtb-****]
module.vpc.aws_route_table.private[1]: Refreshing state... [id=rtb-****]
module.vpc.aws_route_table.public[0]: Refreshing state... [id=rtb-****]
module.vpc.aws_internet_gateway.this[0]: Creating...
module.vpc.aws_subnet.public[0]: Creating...
module.vpc.aws_subnet.private[1]: Creating...
module.vpc.aws_subnet.public[1]: Creating...
module.vpc.aws_subnet.private[0]: Creating...

│ Error: Error creating internet gateway: UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: ENCODED_MESSAGE1
│ Error: error creating subnet: UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: ENCODED_MESSAGE2
│ Error: error creating subnet: UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: ENCODED_MESSAGE3
│ Error: error creating subnet: UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: ENCODED_MESSAGE4
│ Error: error creating subnet: UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: ENCODED_MESSAGE5
>> [LOG]: Getting policy from iamlive:/app/iamlive.log
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "sts:GetCallerIdentity",
                "ec2:DescribeAccountAttributes",
                "ec2:DescribeVpcs",
                "ec2:DescribeVpcAttribute",
                "ec2:DescribeVpcClassicLink",
                "ec2:DescribeVpcClassicLinkDnsSupport",
                "ec2:DescribeRouteTables",
                "ec2:DescribeNetworkAcls",
                "ec2:DescribeSecurityGroups",
                "ec2:CreateInternetGateway",
                "ec2:CreateSubnet"
            ],
            "Resource": "*"
        }
    ]
}
>> [LOG]: Creating IAM policy version to arn:aws:iam::0904********:policy/dummy-user-inline
>> [LOG]: Attempt to delete oldest policy version
>> [LOG]: Deleting policy version id: v225
>> [LOG]: Successfully deleted the policy version id v225
>> [LOG]: Attempt to create the latest policy version
>> [LOG]: No differences between current and latest policies
>> [LOG]: Attempting to decode encoded messages ...
>> [LOG]: Missing permissions:
# Automatically removes duplicated error messages, decreased output from 5 messages to 2
{
  "action": "ec2:CreateTags",
  "resource": "arn:aws:ec2:eu-west-1:0904********:internet-gateway/*"
}
{
  "action": "ec2:CreateTags",
  "resource": "arn:aws:ec2:eu-west-1:0904********:subnet/*"
}
>> [ERROR]: TODO: Handle missing permissions
>> [LOG]: Removing existing iamlive container
```

So it's easy for me to find out which ones are missing, at least for now :)

**Comment by iann0036** [comment]
Neat!

Please shoot through any discrepancies if/when you find them 👍
