### ISSUE TITLE
Error when brew install iann0036/iamlive/iamlive

### ISSUE THREAD

**Issue by PePoDev** [iann0036/iamlive#44]
```
Error: Invalid formula: /home/username/.linuxbrew/Homebrew/Library/Taps/iann0036/homebrew-iamlive/iamlive.rb
formulae require at least a URL
Error: Cannot tap iann0036/iamlive: invalid syntax in tap!
```

**Comment by iann0036** [comment]
Hey @PePoDev,

Just checking you've entered iamlive twice in your command (separated by `/`)?

```
brew install iann0036/iamlive/iamlive
```

Also try running a `brew update` beforehand just in case. Let me know if that helps.

**Comment by iann0036** [comment]
Hey @PePoDev,

Apologies for the late response. Linux brew isn't currently supported, it's probably best you grab one of the binaries from the Release and place it in your $PATH.
