### ISSUE TITLE
Running iamlive in CSM mode in GitHub Actions workflow - SIG does not work

### ISSUE THREAD

**Issue by scott-doyland-burrows** [iann0036/iamlive#45]
Hi,

I am trying to run iamlive as part of a GitHub Actions workflow.  Everything is fine except one important detail, for some reason GitHub Actions does not seem to kill the iamlive process when I send ```kill -SIGHUP```.

I also tried ```SIGTERM``` and ```SIGQUIT``` but to no avail.

The only thing that kills the process is ```SIGKILL``` but that means I do not get an output file produced.

This seems to be some odd behaviour with either the GitHub Actions (I am using a GitHub hosted ubuntu runner).

Would it be possible for iamlive to be updated so it can write to the file while it is running, so there is no need to ```killl``` the process before the file is available?

Thanks.

**Comment by iann0036** [comment]
Hey @scott-doyland-burrows,

I wouldn't mind doing a bit of digging to see why the SIGHUP isn't getting through. Do you happen to have a trimmed down sample workflow that you're testing against?

**Comment by scott-doyland-burrows** [comment]
Sure, I will sort a workflow out today for you.

**Comment by scott-doyland-burrows** [comment]
I setup a really simple workflow - and of course now its working - the SIGHUP gets through...

I am unclear why this is so I need to keep stripping parts out of my original workflow until I get that to work as well.

It is really odd, as I even set a last step in the original workflow just to issue a ```kill -SIGHUP``` directly via bash commands, and it still hasn't worked so far.

**Comment by scott-doyland-burrows** [comment]
So it turned out to be a timing issue.

I was starting iamlive from python, and then sending a SIGTERM from python to stop iamlive.

The python script was sending the SIGTERM but then the python script was continuing immediately after the SIGTERM was sent, it was not waiting for iamlive to actually stop.

This was causing it to look like it wasn't managing to stop iamlive - as I could still see iamlive listed in the process list immediately after the SIGTERM was sent.

I have added a loop to check that the process has been terminated, and now its working fine.  It seems to take a few seconds to terminate it via Python.

Thanks.
