### ISSUE TITLE
Terraform fails on x509 certificate error in proxy mode

### ISSUE THREAD

**Issue by julien-carsique-sonarsource** [iann0036/iamlive#53]
Hi,

Everything works well in csm mode, but the resources are not detailed. 
So I'm trying to use the proxy mode. AWS CLI is working fine. Terraform is working mostly fine except with some modules.

Shell 1)
```
iamlive -set-ini -mode proxy
```
Shell 2)
```
export HTTP_PROXY=http://127.0.0.1:10080
export HTTPS_PROXY=http://127.0.0.1:10080
export AWS_CA_BUNDLE=~/.iamlive/ca.pem
terraform init
terraform apply
```

`terraform init` fails on "Initializing provider plugins...":
```
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider hashicorp/http: could not connect to registry.terraform.io: Failed to request discovery document: Get "https://registry.terraform.io/.well-known/terraform.json": x509: certificate signed by unknown authority
```
And `terraform apply` fails on downloading https://www.gstatic.com/ipranges/cloud.json:
```
│ Error: Error making request: Get "https://www.gstatic.com/ipranges/cloud.json": x509: certificate signed by unknown authority
```

**Comment by iann0036** [comment]
Hey @julien-carsique-sonarsource,

Thanks for raising!

There may be some certificate pinning or similar issues at play. Could you attempt the same but also include the following in your secondary shell:

```
export NO_PROXY=registry.terraform.io,www.gstatic.com
```

**Comment by julien-carsique-sonarsource** [comment]
@iann0036 It works like a charm.
Thank you!
