### ISSUE TITLE
error configuring S3 Backend

### ISSUE THREAD

**Issue by Woolersuk** [iann0036/iamlive#60]
Hi There,

I may be way off here but I'm attempting to use the proxy mode & we have an AWS S3 backend...     when I run the following configurations:

(application console)
```
export HTTP_PROXY=http://127.0.0.1:10080
export HTTPS_PROXY=http://127.0.0.1:10080
export AWS_CA_BUNDLE=~/.iamlive/ca.pem
export NO_PROXY=sts.amazonaws.com,registry.terraform.io
```

I'm seeing the following issue:

```
Initializing the backend...
╷
│ Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.
│ 
│ Please see https://www.terraform.io/docs/language/settings/backends/s3.html
│ for more information about providing credentials.
│ 
│ Error: RequestError: send request failed
│ caused by: Post "https://sts.amazonaws.com/": x509: certificate signed by unknown authority
```

Now this could be because we are using a specific AWS account for our backend, then a different account for our resources (like admin/dev) so maybe there's an issue there?

I did try this as an option during setup: 
(listening console)

```
iamlive --set-ini --mode proxy --output-file policy.json --refresh-rate 1 --sort-alphabetical --bind-addr 127.0.0.1:10080 --ca-bundle ~/.iamlive/ca.pem --ca-key ~/.iamlive/ca.key --account-id 123456789012,987654321098 --force-wildcard-resource
```
or
```
iamlive --set-ini --mode proxy --profile adminaccount,devaccount --output-file policy.json --refresh-rate 1 --sort-alphabetical --bind-addr 127.0.0.1:10080 --ca-bundle ~/.iamlive/ca.pem --ca-key ~/.iamlive/ca.key --account-id 123456789012,987654321098 --force-wildcard-resource
```

(account ids made generic)
I did omit --profile & --account-id in multiple attempts & tried adding them in others but still nothing.

or am I doing something really wrong here?

**Comment by iann0036** [comment]
Hi @Woolersuk,

It looks like your configuration is okay. Your backend might not respect the NO_PROXY environmental variable, and additionally not support overriding your certificate bundle using AWS_CA_BUNDLE.

You could potentially add `~/.iamlive/ca.pem` to your machine's trusted CA authorities (iamlive generates these, but you may also replace with your own keypair) or make changes to allow it to respect the NO_PROXY.

**Comment by Woolersuk** [comment]
Hi @iann0036 

Many thanks for pointing me in the right direction!!

Oddly having NO_PROXY wasn't working, but no_proxy (in lowercase) was all I needed!!

Thanks again. :)
