### ISSUE TITLE
CloudWatch log permissions has a space

### ISSUE THREAD

**Issue by jmahowald-slalom** [iann0036/iamlive#8]
I havne't yet figured out what's different about CloudWatch Logs, but the permissions are coming out as 
                `"cloudwatch logs:DeleteLogGroup"`
`                "cloudwatch logs:ListTagsLogGroup",`

**Comment by iann0036** [comment]
Hey @jmahowald-slalom,

Thanks heaps for raising. Looks like I was missing a few service mappings there. The latest version (v0.13 or HEAD) should have the fixes. Let me know if that solves your issue.

**Comment by jmahowald** [comment]
looks good now, thanks.
